-- RacingIncident
INCIDENT_COUNTDOWN			= 1
INCIDENT_CARROT_GAINED		= 128
INCIDENT_BOSSWARNING		= 129
INCIDENT_CASTLESUMMON		= 158
INCIDENT_SUMMONED			= 159

-- 이제는 RcMissionScriptUtil::Bind()에서 추가하도록 한다.