------------------------------------------------------------
-- PlayerStatus
------------------------------------------------------------
PLAYERSTATUS_FAINT				= 0
PLAYERSTATUS_SLOW				= 1
PLAYERSTATUS_PETRIFY			= 2
PLAYERSTATUS_INVINCIBLE			= 3
PLAYERSTATUS_BLESS				= 4
PLAYERSTATUS_RAGE				= 5
    
------------------------------------------------------------
--		AI SkillType
------------------------------------------------------------
SKILL_TARGET_POSITION			= 0		-- 지상의 한 지점 공격
SKILL_TARGET_OBJECT				= 1		-- 대상 공격
SKILL_TARGET_SELF				= 2		-- self

-- enum eSkillID
SKILLID_FIREBALL				= 1
SKILLID_BREATH					= 2
SKILLID_ARROW					= 3
SKILLID_MELEEATTACK				= 4
SKILLID_EARTHQUAKE				= 5
SKILLID_FIREBOLT				= 6
SKILLID_ARROW_POSITION			= 7
SKILLID_LIGHTNING_ARROW			= 8
SKILLID_SUMMON					= 9
SKILLID_HEALING					= 10
SKILLID_CRITICAL				= 11
SKILLID_CRITICAL_HIT			= 12
SKILLID_LIGHTNING_ARROW_POSITION= 13
SKILLID_FORCE_FIELD				= 14
SKILLID_MONSTER_ARROW			= 15
SKILLID_ATTACK_SOUL				= 16
SKILLID_ATTACK_BLACK			= 17
SKILLID_VOLCANO					= 18
SKILLID_FIREWAVE				= 19
SKILLID_SOULTOUCH				= 20
SKILLID_PETRIFY					= 21
SKILLID_SOULLINK				= 22
SKILLID_GAZE_BEAM				= 23
SKILLID_BODY_ATTACK				= 24
SKILLID_VOLCANO_MOVING			= 25
SKILLID_BODY_HURRICANE			= 26
SKILLID_HEAL_SELF				= 27
SKILLID_HEAL_OTHER				= 28
SKILLID_BODY_PRESS				= 29
SKILLID_TOWER_ARROW				= 30
SKILLID_EAGLE_ARROW				= 31
SKILLID_CHARGEATTACK			= 32
SKILLID_CHARGESIDE				= 33
SKILLID_CHARGEJUMP				= 34
SKILLID_FIRE_SMASH				= 35
SKILLID_TAIL_SPLASH				= 36
SKILLID_FIRE_BREATH				= 37
SKILLID_POWER_ARROW				= 38
SKILLID_TAIL_SPLASH_REFLECT		= 39
SKILLID_TAIL_SPLASH2			= 40
SKILLID_TAIL_SPLASH2_REFLECT	= 41
SKILLID_DRAGON_SLIDING			= 42
SKILLID_SWORD_THROW_HORIZONTAL	= 43
SKILLID_SWORD_THROW_VERTICAL	= 44
SKILLID_SWORD_THROW_CIRCURLAR	= 45
SKILLID_ARROW_MULTISHOT			= 46
SKILLID_MELEEATTACK_CHARGE		= 47
