--ALIGN_H_LEFT      = 0x01,
--ALIGN_H_CENTER    = 0x02,
--ALIGN_H_RIGHT     = 0x04,
--ALIGN_V_TOP       = 0x10,
--ALIGN_V_MIDDLE    = 0x20,
--ALIGN_V_BOTTOM    = 0x40,

ALIGN_LEFT_TOP		= 0x11
ALIGN_LEFT_CENTER	= 0x21
ALIGN_LEFT_BOTTOM	= 0x41
ALIGN_CENTER_TOP	= 0x12
ALIGN_CENTER		= 0x22
ALIGN_CENTER_BOTTOM	= 0x42
ALIGN_RIGHT_TOP		= 0x14
ALIGN_RIGHT_CENTER	= 0x24
ALIGN_RIGHT_BOTTOM	= 0x44

--FT_STYLE_NORMAL		= 0,
--FT_STYLE_THICK		= 1,
--FT_STYLE_OUTLINE	= 2,
--FT_STYLE_SHADOW		= 4,

FT_STYLE_NORMAL			= 0
FT_STYLE_THICK			= 1
FT_STYLE_OUTLINE		= 2
FT_STYLE_THICK_OUTLINE	= 3
FT_STYLE_SHADOW			= 4

-- Refresh
RFOK					= 1
RFCANCEL				= 2
RFYES					= 3
RFNO					= 4

-- RcDynamicFormBase::eFormEvent
RFEVENT_CLOSE			= 1
RFEVENT_SCRIPT			= 2
RFEVENT_SCRIPT_DRAW		= 3
RFEVENT_SCRIPT_LISTCHANGE = 4

UIFORM_INFO				= 0
UIFORM_YESNO			= 1

VK_RETURN				= 0x0D
VK_ESCAPE				= 0x1B

-- UI Types only in lua eventSceneIntro
UI_OVERLAY		= 1
UI_FONT			= 2
UI_TEXT			= 3


